### PR TITLE
Support for Feed Me 2.x

### PR DESCRIPTION
**Pull request by engram-design**
Hi there, 

Just thought to create a PR for the issue [#22](https://github.com/ethercreative/simplemap/issues/22).

I'm not sure if you plan on implementing this via JS (checking if an address value is empty, but valid lng/lat values), but this is probably a more case-specific fix.

Please also refer to the [Feed Me 2.0 Field Types Docs](http://sgroup.com.au/plugins/feedme/developers/field-types). You're more than welcome to shift things to suite your needs.

So - what this PR does it enable support for Feed Me 2. When mapping data to a SimpleMap field, you'll get the following 4 options:

screen shot 2016-12-21 at 12 17 34 pm

In addition - the import process (implemented in `SimpleMap_MapFeedMeFieldType.php`), will actually check data for `address`, `lng`, and `lat`, and fill in any missing information. This is important where other systems might only provide one or the other values.

### CODE REVIEW

**Comment by shornuk** [comment]
This is great. Tested on my install and works great. Makes mapping location data a lot easier. 
Only other thing needed is to create the `parts` in the same way that the `address` is created from a supplied Lat/Lng, as I think the `parts` is one of the most valuable elements of Simplemap. I think that would make it complete and super useful.

**Comment by engram-design** [comment]
@shornuk Have a look at the latest PR which adds this in for you. Again - the developers might like to clean this up and put their own code to use for a proper commit.

**Comment by shornuk** [comment]
Tested and working like a charm! :)

**Comment by Tam** [comment]
We've manually added this to v1.5.0, thanks!

**Pull request closed without merging**
